"""Added enrollment_type column to CorseMembers model

Revision ID: 1af197326541
Revises: 
Create Date: 2024-08-10 17:04:52.403427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1af197326541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('event_id')

    with op.batch_alter_table('course_details', schema=None) as batch_op:
        batch_op.alter_column('instructor_email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('course_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_type', sa.String(length=150), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('calendar_type')
        batch_op.drop_column('password')
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('calendar_type', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('course_members', schema=None) as batch_op:
        batch_op.drop_column('enrollment_type')

    with op.batch_alter_table('course_details', schema=None) as batch_op:
        batch_op.alter_column('instructor_email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
